
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: micro
  labels:
    app: micro
spec:
  selector:
    matchLabels:
      app: micro
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: micro
    spec:
      containers:
      - name: micro
        image: mtouhin/micro
        ports:
        - containerPort: 80
        env:
          - name: key_id
            value: "AKIATFDQCUG2Q4Z4ZEWK"
          - name: secret_key
            value: "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"