
apiVersion: v1
kind: Service
metadata:
  name: micro
  namespace: default
  labels:
    app: micro
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: micro
  type: LoadBalancer